# specify docker as a dependency
sudo: required
services:
  - docker

# build test version of React
before_install:
  - docker build -t jamiesonbates/react-test -f ./client/Dockerfile.dev ./client


# Run tests
script:
  - docker run -e CI=true jamiesonbates/react-test npm test

# Build prod versions of all projects
after_success:
  - docker build -t jamiesonbates/multi-client ./client
  - docker build -t jamiesonbates/multi-nginx ./nginx
  - docker build -t jamiesonbates/multi-server ./server
  - docker build -t jamiesonbates/multi-worker ./worker
  # login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push all to docker hub
  - docker push jamiesonbates/multi-client
  - docker push jamiesonbates/multi-nginx
  - docker push jamiesonbates/multi-server
  - docker push jamiesonbates/multi-worker


# Tell Elastic Beanstalk to update
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-us-east-1-509436554991
  bucket_path: multi-docker # same as app name
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
